<aside class="col col-span3">
    <h2>JS Libs</h2>
    <p>
        This is the jsLibraries used in the examples.
    </p>

    <dl class="libs-list">
        <dt>
            <a href="http://jquery.com/">jQuery</a>    
        </dt>
        <dd>
            jQuery is a fast, small, and feature-rich JavaScript library. 
            It makes things like HTML document traversal and manipulation, event handling, animation, 
            and Ajax much simpler with an easy-to-use API that works across a multitude of browsers. 
            With a combination of versatility and extensibility, jQuery has changed the way that millions of people write JavaScript.
        </dd>
        <dt>
            <a href="http://fgnass.github.io/spin.js/">Spin.js</a>    
        </dt>
        <dd>
            Spin.js dynamically creates spinning activity indicators that can be used as resolution-independent replacement for AJAX loading GIFs.
        </dd>
        <!--<dt>
            <a href="http://handlebarsjs.com/">Handlebarsjs</a>
        </dt>
        <dd>
            Handlebars provides the power necessary to let you build semantic templates effectively with no frustration.
        </dd>-->
    </dl>
</aside>
