<nav class="col colSpan2 submenu">
    <ul>
        <li>
            <a href="/pages/styleguide.phtml">Styleguide</a>
        </li>
        <li>
            <a href="/pages/spinner.phtml">Spinner <span class="smaller">(ajaxloader)</span></a>
        </li>
        <li>
          <a href="/pages/spinnerCss.phtml">SpinnerCss <span class="smaller">(ajaxloader)</span></a>
        </li>
        <li>
            <a href="/pages/filter-blur.phtml">Filter-blur</a>
        </li>
        <li>
            <a href="/pages/googleMaps.phtml">Google maps</a>
        </li>
        <li>
            <a href="/pages/flex-box.phtml">Flex-box</a>
        </li>
        <li>
            <a href="/pages/fontawsome.phtml">Fontawsome</a>
        </li>
        <li>
            <a href="/pages/video.phtml">Video (tag)</a>
        </li>
      <li>
        <a href="/pages/parallax.phtml">Parallax (scroll)</a>
      </li>
      <li>
        <a href="/pages/inputStuff.phtml">inputStuff</a>
      </li>
    </ul>
</nav>