<nav class="col submenu">
    <ul>
        <li>
            <a href="/pages/styleguide.phtml">Styleguide</a>
        </li>
        <li>
            <a href="/pages/spinner.phtml">Spinner <span class="smaller">(ajaxloader)</span></a>
        </li>
        <li>
            <a href="/pages/filter-blur.phtml">Filter-blur</a>
        </li>
        <li>
            <a href="/pages/googleMaps.phtml">Google maps</a>
        </li>
    </ul>
</nav>