<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Default Web</title>
	<!-- include("/blocks/styles.phtml") -->
</head>
<body>

   <!-- include("/blocks/ieScripts.phtml") --> 
    
   <!-- include("/blocks/header.phtml") -->

    <div class="mainContent">
        <div class="section row">
            <div class="outerGridWrapRow">
                <!-- include("/blocks/submenu.phtml") -->

				<article class="col colSpan7">
					<!-- [phtml:content] -->
				</article>

				<!-- include("/blocks/aside.phtml") -->
            </div>
        </div>
    </div>

    <!-- include("/blocks/footer.phtml") -->
    
	<!-- include("/blocks/scripts.phtml") -->
</body>
</html>
