<!-- layout("/pages/layout/index.phtml") -->

<h1>Filter-blur</h1>
<p>
    A less/js thingy that makes stuff blurry in most browsers
</p>
    
<p class="uses">
    <a href="/UI/less/mixins/filter.blur.less">filter.blur.less</a>
    <a href="/UI/js/svg.filter.blur.js">css.filter.blur.js</a> (for ie 10 and 11)
    <a href="/UI/js/lib/ieVersion.js">ieVersion.js</a>
</p>
    
<ol class="examplesList">
    <li>
        <h2>Blur 10px</h2>
        <img alt="Filter-blur test" src="http://loremflickr.com/600/800/fish" class="blur-test-10" data-ie-blur="10" />
    </li>
    <li>
        <h2>Blur 15px</h2>
        <img alt="Filter-blur test" src="http://loremflickr.com/600/800/microphone" class="blur-test-15" data-ie-blur="15" />
    </li>
    <li>
        <h2>Blur 20px</h2>
        <img alt="Filter-blur test" src="http://loremflickr.com/600/800/drum" class="blur-test-20" data-ie-blur="20" />
    </li>
</ol>