<!-- layout("/pages/layout/index.phtml") -->

<h1>Flex-box test</h1>

<div class="flex-box">
  <div class="flex-test-1">
    <div class="box">
      flex-box 1
    </div>
    <div class="box">
      flex-box 2
    </div>
    <div class="box">
      flex-box 3
    </div>
    <div class="box">
      flex-box 4
    </div>
    <div class="box">
      flex-box 5
    </div>
    <div class="box">
      flex-box 6
    </div>
  </div>
</div>