<!-- layout("/pages/layout/index.phtml") -->

<h1>Fontawsome examples</h1>
<p>v 4.4.0</p>

<div class="row fontawsome">
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf26e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf042;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf170;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf037;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf039;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf036;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf038;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf270;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf13d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf17b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf209;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf103;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf100;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf101;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf102;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf107;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf104;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf105;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf106;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf179;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf187;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1fe;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ab;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a8;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf01a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf190;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf18e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf01b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0aa;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf063;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf060;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf061;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf062;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf047;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0b2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf07e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf07d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf069;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1fa;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf04a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf24e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf05e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf080;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf080;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf02a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf244;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf243;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf242;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf241;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf240;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf244;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf240;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf242;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf243;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf241;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf236;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0fc;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf206;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1fd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf171;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf172;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf15a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf27e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf032;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf02d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf02e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf097;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0b1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf15a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf188;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ad;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf140;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf207;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf20d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ba;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ec;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf073;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf274;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf272;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf133;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf271;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf273;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf030;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf083;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0da;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf150;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf191;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf152;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf151;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf218;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf217;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf20a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f3;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf24c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf24b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf127;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf058;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf05d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf14a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf046;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf13a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf137;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf138;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf139;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf078;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf053;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf054;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf077;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ae;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf268;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf111;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf10c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ce;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1db;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ea;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf017;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf24d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ed;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ee;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf121;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf126;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cb;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f4;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf013;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf085;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0db;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf075;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf27a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf27b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf086;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e6;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf14e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf066;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf20e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf26d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf25e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf125;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf05b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf13c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c4;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf210;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf108;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1bd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf219;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a6;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf155;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf192;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf019;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf17d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf16b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf044;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf052;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf141;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf142;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf003;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf199;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf12d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf153;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf153;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ec;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf12a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf06a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf071;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf065;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf23e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf08e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf14c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf06e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf070;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1fb;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf230;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf082;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf049;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf050;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ac;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf182;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0fb;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf15b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c3;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c8;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf016;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf15c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1c6;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf008;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0b0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf06d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf134;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf269;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf024;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf11e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf11d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf16e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf07b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf114;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf07c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf115;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf031;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf280;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf211;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf04e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf180;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf119;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf11b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf154;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf013;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf085;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf22d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf265;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf260;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf261;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf06b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d3;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf113;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf092;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf184;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf000;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ac;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ee;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf184;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0fd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf255;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf258;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a4;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf256;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf25b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf25a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf255;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf257;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf259;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf256;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0a0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1dc;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf025;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf004;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf08a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf21e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1da;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf015;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf236;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf254;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf251;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf252;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf253;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf253;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf252;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf250;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf251;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf27c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf13b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf246;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf20b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf01c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf275;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf129;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf05a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf156;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf16d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf26b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf224;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf208;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf033;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1aa;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cc;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf084;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf11c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf159;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ab;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf109;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf202;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf203;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf06c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf212;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf094;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf149;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf148;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0eb;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf201;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf08c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf17c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf022;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0cb;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ca;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf124;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf023;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf175;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf177;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf178;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf176;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf076;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf064;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf112;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf122;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf183;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf279;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf041;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf278;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf276;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf277;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf222;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf227;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf229;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf22b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf22a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf136;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf20c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf23a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0fa;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf11a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf223;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf130;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf131;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf068;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf056;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf146;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf147;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf10b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf10b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d6;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf186;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf21c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf245;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf001;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf22c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ea;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf247;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf248;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf263;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf264;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf23d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf26a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf23c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf18c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1fc;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1dd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ea;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf04c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ed;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf040;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf14b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf044;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf095;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf098;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf200;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a8;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf231;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf072;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf04b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf144;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf01d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e6;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf067;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf055;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0fe;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf196;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf011;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf02f;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf12e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d6;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf029;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf128;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf059;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf10d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf10e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d0;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf074;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf021;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf25d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf18b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf01e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf112;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf122;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf079;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf018;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf135;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf01e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf158;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf143;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf158;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf158;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf156;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf267;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c4;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf002;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf010;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf213;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf233;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf064;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e1;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf14d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf045;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf20b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf20b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf132;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf21a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf214;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf07a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf090;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf08b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf012;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf215;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf216;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf17e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf198;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1de;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf118;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0dc;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf15d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf15e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf160;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf161;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0de;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0dd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0dd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf162;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf163;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0de;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1be;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf197;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf110;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1bc;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c8;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf096;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf18d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf16c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf005;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf089;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf123;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf123;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf123;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf006;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1b7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf048;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf051;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf249;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf24a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf04d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf21d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0cc;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1a3;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf12c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf239;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f2;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf185;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf12b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ce;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf10a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e4;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf02b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf02c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ae;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ba;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf26c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d5;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf120;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf034;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf035;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf009;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00b;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf08d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf165;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf088;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf087;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf164;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf145;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf00d;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf057;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf05c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf043;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf150;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf191;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf204;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf205;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf152;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf151;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf25c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf238;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf224;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf225;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1f8;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf014;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1bb;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf181;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf262;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf091;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0d1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf195;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e4;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf173;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf174;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf195;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf26c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e8;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf099;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf081;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0cd;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0e2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf127;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf09c;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf13e;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0dc;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf093;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf155;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf007;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0f0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf234;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf21b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf235;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0c0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf221;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf226;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf228;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf237;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf03d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf27d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf194;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1ca;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf189;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf027;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf026;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf028;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf071;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d7;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf18a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i>
      <span>[&amp;#xf232;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i>
      <span>[&amp;#xf193;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1eb;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf266;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf17a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf159;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf0ad;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf168;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf169;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf23b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf19e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i>
      <span>[&amp;#xf23b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i>
      <span>[&amp;#xf1d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i>
      <span>[&amp;#xf1e9;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf167;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf16a;]</span>
    </div>
    
    <div class="faBox">
      <i class="fa"></i>
      <span>[&amp;#xf166;]</span>
    </div>
    
  </div>