<!-- layout("/pages/layout/index.phtml") -->

<h1>Current Fontawsome version:</h1>
<p>v 4.5.0</p>

<p>
  <a href="http://fontawesome.io/cheatsheet/" target="_blank">http://fontawesome.io/cheatsheet/</a>
</p>

<p>
  The following list is just some fontawsome examples.
</p>

<p>
  <ul class="icon-test">
    <li>&#xf095; (4.0)</li>
    <li>&#xf19d; (4.1)</li>
    <li>&#xf1e5; (4.2)</li>
    <li>&#xf218; (4.3)</li>
    <li>&#xf272; (4.4)</li>

    <li>&#xf28b; (4.5)</li>
  </ul>
</p>

