<!-- layout("/pages/layout/index.phtml") -->

<h1>Fontawsome examples</h1>
<p>v 4.4.0</p>

<div class="row fontawsome">
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-500px
      
      --><span>[&amp;#xf26e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-adjust
      
      --><span>[&amp;#xf042;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-adn
      
      --><span>[&amp;#xf170;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-align-center
      
      --><span>[&amp;#xf037;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-align-justify
      
      --><span>[&amp;#xf039;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-align-left
      
      --><span>[&amp;#xf036;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-align-right
      
      --><span>[&amp;#xf038;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-amazon
      
      --><span>[&amp;#xf270;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-ambulance
      
      --><span>[&amp;#xf0f9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-anchor
      
      --><span>[&amp;#xf13d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-android
      
      --><span>[&amp;#xf17b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-angellist
      
      --><span>[&amp;#xf209;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-double-down
      
      --><span>[&amp;#xf103;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-double-left
      
      --><span>[&amp;#xf100;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-double-right
      
      --><span>[&amp;#xf101;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-double-up
      
      --><span>[&amp;#xf102;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-down
      
      --><span>[&amp;#xf107;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-left
      
      --><span>[&amp;#xf104;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-right
      
      --><span>[&amp;#xf105;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-angle-up
      
      --><span>[&amp;#xf106;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-apple
      
      --><span>[&amp;#xf179;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-archive
      
      --><span>[&amp;#xf187;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-area-chart
      
      --><span>[&amp;#xf1fe;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-circle-down
      
      --><span>[&amp;#xf0ab;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-circle-left
      
      --><span>[&amp;#xf0a8;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-circle-o-down
      
      --><span>[&amp;#xf01a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-arrow-circle-o-left
      
      --><span>[&amp;#xf190;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-arrow-circle-o-right
      
      --><span>[&amp;#xf18e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-circle-o-up
      
      --><span>[&amp;#xf01b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-circle-right
      
      --><span>[&amp;#xf0a9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-circle-up
      
      --><span>[&amp;#xf0aa;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-down
      
      --><span>[&amp;#xf063;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-left
      
      --><span>[&amp;#xf060;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-right
      
      --><span>[&amp;#xf061;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrow-up
      
      --><span>[&amp;#xf062;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrows
      
      --><span>[&amp;#xf047;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrows-alt
      
      --><span>[&amp;#xf0b2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrows-h
      
      --><span>[&amp;#xf07e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-arrows-v
      
      --><span>[&amp;#xf07d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-asterisk
      
      --><span>[&amp;#xf069;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-at
      
      --><span>[&amp;#xf1fa;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-automobile
       
      --><span>[&amp;#xf1b9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-backward
      
      --><span>[&amp;#xf04a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-balance-scale
      
      --><span>[&amp;#xf24e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-ban
      
      --><span>[&amp;#xf05e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-bank
       
      --><span>[&amp;#xf19c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bar-chart
      
      --><span>[&amp;#xf080;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bar-chart-o
       
      --><span>[&amp;#xf080;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-barcode
      
      --><span>[&amp;#xf02a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bars
      
      --><span>[&amp;#xf0c9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-0
       
      --><span>[&amp;#xf244;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-1
       
      --><span>[&amp;#xf243;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-2
       
      --><span>[&amp;#xf242;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-3
       
      --><span>[&amp;#xf241;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-4
       
      --><span>[&amp;#xf240;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-empty
      
      --><span>[&amp;#xf244;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-full
      
      --><span>[&amp;#xf240;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-half
      
      --><span>[&amp;#xf242;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-quarter
      
      --><span>[&amp;#xf243;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-battery-three-quarters
      
      --><span>[&amp;#xf241;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-bed
      
      --><span>[&amp;#xf236;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-beer
      
      --><span>[&amp;#xf0fc;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-behance
      
      --><span>[&amp;#xf1b4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-behance-square
      
      --><span>[&amp;#xf1b5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bell
      
      --><span>[&amp;#xf0f3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bell-o
      
      --><span>[&amp;#xf0a2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-bell-slash
      
      --><span>[&amp;#xf1f6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-bell-slash-o
      
      --><span>[&amp;#xf1f7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-bicycle
      
      --><span>[&amp;#xf206;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-binoculars
      
      --><span>[&amp;#xf1e5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-birthday-cake
      
      --><span>[&amp;#xf1fd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bitbucket
      
      --><span>[&amp;#xf171;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bitbucket-square
      
      --><span>[&amp;#xf172;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bitcoin
       
      --><span>[&amp;#xf15a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-black-tie
      
      --><span>[&amp;#xf27e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bold
      
      --><span>[&amp;#xf032;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bolt
      
      --><span>[&amp;#xf0e7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-bomb
      
      --><span>[&amp;#xf1e2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-book
      
      --><span>[&amp;#xf02d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bookmark
      
      --><span>[&amp;#xf02e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bookmark-o
      
      --><span>[&amp;#xf097;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-briefcase
      
      --><span>[&amp;#xf0b1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-btc
      
      --><span>[&amp;#xf15a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bug
      
      --><span>[&amp;#xf188;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-building
      
      --><span>[&amp;#xf1ad;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-building-o
      
      --><span>[&amp;#xf0f7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bullhorn
      
      --><span>[&amp;#xf0a1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-bullseye
      
      --><span>[&amp;#xf140;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-bus
      
      --><span>[&amp;#xf207;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-buysellads
      
      --><span>[&amp;#xf20d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-cab
       
      --><span>[&amp;#xf1ba;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-calculator
      
      --><span>[&amp;#xf1ec;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-calendar
      
      --><span>[&amp;#xf073;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-calendar-check-o
      
      --><span>[&amp;#xf274;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-calendar-minus-o
      
      --><span>[&amp;#xf272;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-calendar-o
      
      --><span>[&amp;#xf133;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-calendar-plus-o
      
      --><span>[&amp;#xf271;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-calendar-times-o
      
      --><span>[&amp;#xf273;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-camera
      
      --><span>[&amp;#xf030;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-camera-retro
      
      --><span>[&amp;#xf083;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-car
      
      --><span>[&amp;#xf1b9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-down
      
      --><span>[&amp;#xf0d7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-left
      
      --><span>[&amp;#xf0d9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-right
      
      --><span>[&amp;#xf0da;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-square-o-down
      
      --><span>[&amp;#xf150;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-caret-square-o-left
      
      --><span>[&amp;#xf191;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-square-o-right
      
      --><span>[&amp;#xf152;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-square-o-up
      
      --><span>[&amp;#xf151;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-caret-up
      
      --><span>[&amp;#xf0d8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-cart-arrow-down
      
      --><span>[&amp;#xf218;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-cart-plus
      
      --><span>[&amp;#xf217;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc
      
      --><span>[&amp;#xf20a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc-amex
      
      --><span>[&amp;#xf1f3;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-cc-diners-club
      
      --><span>[&amp;#xf24c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc-discover
      
      --><span>[&amp;#xf1f2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-cc-jcb
      
      --><span>[&amp;#xf24b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc-mastercard
      
      --><span>[&amp;#xf1f1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc-paypal
      
      --><span>[&amp;#xf1f4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc-stripe
      
      --><span>[&amp;#xf1f5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-cc-visa
      
      --><span>[&amp;#xf1f0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-certificate
      
      --><span>[&amp;#xf0a3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chain
       
      --><span>[&amp;#xf0c1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chain-broken
      
      --><span>[&amp;#xf127;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-check
      
      --><span>[&amp;#xf00c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-check-circle
      
      --><span>[&amp;#xf058;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-check-circle-o
      
      --><span>[&amp;#xf05d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-check-square
      
      --><span>[&amp;#xf14a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-check-square-o
      
      --><span>[&amp;#xf046;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-circle-down
      
      --><span>[&amp;#xf13a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-circle-left
      
      --><span>[&amp;#xf137;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-circle-right
      
      --><span>[&amp;#xf138;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-circle-up
      
      --><span>[&amp;#xf139;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-down
      
      --><span>[&amp;#xf078;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-left
      
      --><span>[&amp;#xf053;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-right
      
      --><span>[&amp;#xf054;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-chevron-up
      
      --><span>[&amp;#xf077;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-child
      
      --><span>[&amp;#xf1ae;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-chrome
      
      --><span>[&amp;#xf268;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-circle
      
      --><span>[&amp;#xf111;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-circle-o
      
      --><span>[&amp;#xf10c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-circle-o-notch
      
      --><span>[&amp;#xf1ce;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-circle-thin
      
      --><span>[&amp;#xf1db;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-clipboard
      
      --><span>[&amp;#xf0ea;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-clock-o
      
      --><span>[&amp;#xf017;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-clone
      
      --><span>[&amp;#xf24d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-close
       
      --><span>[&amp;#xf00d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cloud
      
      --><span>[&amp;#xf0c2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cloud-download
      
      --><span>[&amp;#xf0ed;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cloud-upload
      
      --><span>[&amp;#xf0ee;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cny
       
      --><span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-code
      
      --><span>[&amp;#xf121;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-code-fork
      
      --><span>[&amp;#xf126;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-codepen
      
      --><span>[&amp;#xf1cb;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-coffee
      
      --><span>[&amp;#xf0f4;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cog
      
      --><span>[&amp;#xf013;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cogs
      
      --><span>[&amp;#xf085;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-columns
      
      --><span>[&amp;#xf0db;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-comment
      
      --><span>[&amp;#xf075;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-comment-o
      
      --><span>[&amp;#xf0e5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-commenting
      
      --><span>[&amp;#xf27a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-commenting-o
      
      --><span>[&amp;#xf27b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-comments
      
      --><span>[&amp;#xf086;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-comments-o
      
      --><span>[&amp;#xf0e6;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-compass
      
      --><span>[&amp;#xf14e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-compress
      
      --><span>[&amp;#xf066;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-connectdevelop
      
      --><span>[&amp;#xf20e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-contao
      
      --><span>[&amp;#xf26d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-copy
       
      --><span>[&amp;#xf0c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-copyright
      
      --><span>[&amp;#xf1f9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-creative-commons
      
      --><span>[&amp;#xf25e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-credit-card
      
      --><span>[&amp;#xf09d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-crop
      
      --><span>[&amp;#xf125;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-crosshairs
      
      --><span>[&amp;#xf05b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-css3
      
      --><span>[&amp;#xf13c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-cube
      
      --><span>[&amp;#xf1b2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-cubes
      
      --><span>[&amp;#xf1b3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cut
       
      --><span>[&amp;#xf0c4;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-cutlery
      
      --><span>[&amp;#xf0f5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-dashboard
       
      --><span>[&amp;#xf0e4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-dashcube
      
      --><span>[&amp;#xf210;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-database
      
      --><span>[&amp;#xf1c0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-dedent
       
      --><span>[&amp;#xf03b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-delicious
      
      --><span>[&amp;#xf1a5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-desktop
      
      --><span>[&amp;#xf108;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-deviantart
      
      --><span>[&amp;#xf1bd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-diamond
      
      --><span>[&amp;#xf219;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-digg
      
      --><span>[&amp;#xf1a6;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-dollar
       
      --><span>[&amp;#xf155;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-dot-circle-o
      
      --><span>[&amp;#xf192;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-download
      
      --><span>[&amp;#xf019;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-dribbble
      
      --><span>[&amp;#xf17d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-dropbox
      
      --><span>[&amp;#xf16b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-drupal
      
      --><span>[&amp;#xf1a9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-edit
       
      --><span>[&amp;#xf044;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-eject
      
      --><span>[&amp;#xf052;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-ellipsis-h
      
      --><span>[&amp;#xf141;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-ellipsis-v
      
      --><span>[&amp;#xf142;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-empire
      
      --><span>[&amp;#xf1d1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-envelope
      
      --><span>[&amp;#xf0e0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-envelope-o
      
      --><span>[&amp;#xf003;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-envelope-square
      
      --><span>[&amp;#xf199;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-eraser
      
      --><span>[&amp;#xf12d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-eur
      
      --><span>[&amp;#xf153;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-euro
       
      --><span>[&amp;#xf153;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-exchange
      
      --><span>[&amp;#xf0ec;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-exclamation
      
      --><span>[&amp;#xf12a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-exclamation-circle
      
      --><span>[&amp;#xf06a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-exclamation-triangle
      
      --><span>[&amp;#xf071;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-expand
      
      --><span>[&amp;#xf065;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-expeditedssl
      
      --><span>[&amp;#xf23e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-external-link
      
      --><span>[&amp;#xf08e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-external-link-square
      
      --><span>[&amp;#xf14c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-eye
      
      --><span>[&amp;#xf06e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-eye-slash
      
      --><span>[&amp;#xf070;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-eyedropper
      
      --><span>[&amp;#xf1fb;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-facebook
      
      --><span>[&amp;#xf09a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-facebook-f
       
      --><span>[&amp;#xf09a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-facebook-official
      
      --><span>[&amp;#xf230;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-facebook-square
      
      --><span>[&amp;#xf082;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-fast-backward
      
      --><span>[&amp;#xf049;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-fast-forward
      
      --><span>[&amp;#xf050;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-fax
      
      --><span>[&amp;#xf1ac;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-feed
       
      --><span>[&amp;#xf09e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-female
      
      --><span>[&amp;#xf182;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-fighter-jet
      
      --><span>[&amp;#xf0fb;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-file
      
      --><span>[&amp;#xf15b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-archive-o
      
      --><span>[&amp;#xf1c6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-audio-o
      
      --><span>[&amp;#xf1c7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-code-o
      
      --><span>[&amp;#xf1c9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-excel-o
      
      --><span>[&amp;#xf1c3;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-image-o
      
      --><span>[&amp;#xf1c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-movie-o
       
      --><span>[&amp;#xf1c8;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-file-o
      
      --><span>[&amp;#xf016;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-pdf-o
      
      --><span>[&amp;#xf1c1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-photo-o
       
      --><span>[&amp;#xf1c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-picture-o
       
      --><span>[&amp;#xf1c5;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-powerpoint-o
      
      --><span>[&amp;#xf1c4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-sound-o
       
      --><span>[&amp;#xf1c7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-file-text
      
      --><span>[&amp;#xf15c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-file-text-o
      
      --><span>[&amp;#xf0f6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-video-o
      
      --><span>[&amp;#xf1c8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-word-o
      
      --><span>[&amp;#xf1c2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-file-zip-o
       
      --><span>[&amp;#xf1c6;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-files-o
      
      --><span>[&amp;#xf0c5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-film
      
      --><span>[&amp;#xf008;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-filter
      
      --><span>[&amp;#xf0b0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-fire
      
      --><span>[&amp;#xf06d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-fire-extinguisher
      
      --><span>[&amp;#xf134;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-firefox
      
      --><span>[&amp;#xf269;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-flag
      
      --><span>[&amp;#xf024;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-flag-checkered
      
      --><span>[&amp;#xf11e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-flag-o
      
      --><span>[&amp;#xf11d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-flash
       
      --><span>[&amp;#xf0e7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-flask
      
      --><span>[&amp;#xf0c3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-flickr
      
      --><span>[&amp;#xf16e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-floppy-o
      
      --><span>[&amp;#xf0c7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-folder
      
      --><span>[&amp;#xf07b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-folder-o
      
      --><span>[&amp;#xf114;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-folder-open
      
      --><span>[&amp;#xf07c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-folder-open-o
      
      --><span>[&amp;#xf115;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-font
      
      --><span>[&amp;#xf031;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-fonticons
      
      --><span>[&amp;#xf280;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-forumbee
      
      --><span>[&amp;#xf211;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-forward
      
      --><span>[&amp;#xf04e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-foursquare
      
      --><span>[&amp;#xf180;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-frown-o
      
      --><span>[&amp;#xf119;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-futbol-o
      
      --><span>[&amp;#xf1e3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gamepad
      
      --><span>[&amp;#xf11b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gavel
      
      --><span>[&amp;#xf0e3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gbp
      
      --><span>[&amp;#xf154;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-ge
       
      --><span>[&amp;#xf1d1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gear
       
      --><span>[&amp;#xf013;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gears
       
      --><span>[&amp;#xf085;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-genderless
      
      --><span>[&amp;#xf22d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-get-pocket
      
      --><span>[&amp;#xf265;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-gg
      
      --><span>[&amp;#xf260;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-gg-circle
      
      --><span>[&amp;#xf261;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gift
      
      --><span>[&amp;#xf06b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-git
      
      --><span>[&amp;#xf1d3;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-git-square
      
      --><span>[&amp;#xf1d2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-github
      
      --><span>[&amp;#xf09b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-github-alt
      
      --><span>[&amp;#xf113;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-github-square
      
      --><span>[&amp;#xf092;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gittip
       
      --><span>[&amp;#xf184;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-glass
      
      --><span>[&amp;#xf000;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-globe
      
      --><span>[&amp;#xf0ac;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-google
      
      --><span>[&amp;#xf1a0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-google-plus
      
      --><span>[&amp;#xf0d5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-google-plus-square
      
      --><span>[&amp;#xf0d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-google-wallet
      
      --><span>[&amp;#xf1ee;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-graduation-cap
      
      --><span>[&amp;#xf19d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-gratipay
      
      --><span>[&amp;#xf184;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-group
       
      --><span>[&amp;#xf0c0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-h-square
      
      --><span>[&amp;#xf0fd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-hacker-news
      
      --><span>[&amp;#xf1d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-grab-o
       
      --><span>[&amp;#xf255;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-lizard-o
      
      --><span>[&amp;#xf258;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-hand-o-down
      
      --><span>[&amp;#xf0a7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-hand-o-left
      
      --><span>[&amp;#xf0a5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-hand-o-right
      
      --><span>[&amp;#xf0a4;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-hand-o-up
      
      --><span>[&amp;#xf0a6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-paper-o
      
      --><span>[&amp;#xf256;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-peace-o
      
      --><span>[&amp;#xf25b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-pointer-o
      
      --><span>[&amp;#xf25a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-rock-o
      
      --><span>[&amp;#xf255;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-scissors-o
      
      --><span>[&amp;#xf257;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-spock-o
      
      --><span>[&amp;#xf259;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hand-stop-o
       
      --><span>[&amp;#xf256;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-hdd-o
      
      --><span>[&amp;#xf0a0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-header
      
      --><span>[&amp;#xf1dc;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-headphones
      
      --><span>[&amp;#xf025;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-heart
      
      --><span>[&amp;#xf004;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-heart-o
      
      --><span>[&amp;#xf08a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-heartbeat
      
      --><span>[&amp;#xf21e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-history
      
      --><span>[&amp;#xf1da;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-home
      
      --><span>[&amp;#xf015;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-hospital-o
      
      --><span>[&amp;#xf0f8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-hotel
       
      --><span>[&amp;#xf236;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass
      
      --><span>[&amp;#xf254;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-1
       
      --><span>[&amp;#xf251;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-2
       
      --><span>[&amp;#xf252;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-3
       
      --><span>[&amp;#xf253;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-end
      
      --><span>[&amp;#xf253;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-half
      
      --><span>[&amp;#xf252;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-o
      
      --><span>[&amp;#xf250;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-hourglass-start
      
      --><span>[&amp;#xf251;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-houzz
      
      --><span>[&amp;#xf27c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-html5
      
      --><span>[&amp;#xf13b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-i-cursor
      
      --><span>[&amp;#xf246;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-ils
      
      --><span>[&amp;#xf20b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-image
       
      --><span>[&amp;#xf03e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-inbox
      
      --><span>[&amp;#xf01c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-indent
      
      --><span>[&amp;#xf03c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-industry
      
      --><span>[&amp;#xf275;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-info
      
      --><span>[&amp;#xf129;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-info-circle
      
      --><span>[&amp;#xf05a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-inr
      
      --><span>[&amp;#xf156;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-instagram
      
      --><span>[&amp;#xf16d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-institution
       
      --><span>[&amp;#xf19c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-internet-explorer
      
      --><span>[&amp;#xf26b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-intersex
       
      --><span>[&amp;#xf224;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-ioxhost
      
      --><span>[&amp;#xf208;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-italic
      
      --><span>[&amp;#xf033;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-joomla
      
      --><span>[&amp;#xf1aa;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-jpy
      
      --><span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-jsfiddle
      
      --><span>[&amp;#xf1cc;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-key
      
      --><span>[&amp;#xf084;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-keyboard-o
      
      --><span>[&amp;#xf11c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-krw
      
      --><span>[&amp;#xf159;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-language
      
      --><span>[&amp;#xf1ab;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-laptop
      
      --><span>[&amp;#xf109;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-lastfm
      
      --><span>[&amp;#xf202;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-lastfm-square
      
      --><span>[&amp;#xf203;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-leaf
      
      --><span>[&amp;#xf06c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-leanpub
      
      --><span>[&amp;#xf212;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-legal
       
      --><span>[&amp;#xf0e3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-lemon-o
      
      --><span>[&amp;#xf094;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-level-down
      
      --><span>[&amp;#xf149;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-level-up
      
      --><span>[&amp;#xf148;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-life-bouy
       
      --><span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-life-buoy
       
      --><span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-life-ring
      
      --><span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-life-saver
       
      --><span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-lightbulb-o
      
      --><span>[&amp;#xf0eb;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-line-chart
      
      --><span>[&amp;#xf201;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-link
      
      --><span>[&amp;#xf0c1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-linkedin
      
      --><span>[&amp;#xf0e1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-linkedin-square
      
      --><span>[&amp;#xf08c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-linux
      
      --><span>[&amp;#xf17c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-list
      
      --><span>[&amp;#xf03a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-list-alt
      
      --><span>[&amp;#xf022;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-list-ol
      
      --><span>[&amp;#xf0cb;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-list-ul
      
      --><span>[&amp;#xf0ca;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-location-arrow
      
      --><span>[&amp;#xf124;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-lock
      
      --><span>[&amp;#xf023;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-long-arrow-down
      
      --><span>[&amp;#xf175;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-long-arrow-left
      
      --><span>[&amp;#xf177;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-long-arrow-right
      
      --><span>[&amp;#xf178;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-long-arrow-up
      
      --><span>[&amp;#xf176;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-magic
      
      --><span>[&amp;#xf0d0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-magnet
      
      --><span>[&amp;#xf076;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-mail-forward
       
      --><span>[&amp;#xf064;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-mail-reply
       
      --><span>[&amp;#xf112;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-mail-reply-all
       
      --><span>[&amp;#xf122;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-male
      
      --><span>[&amp;#xf183;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-map
      
      --><span>[&amp;#xf279;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-map-marker
      
      --><span>[&amp;#xf041;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-map-o
      
      --><span>[&amp;#xf278;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-map-pin
      
      --><span>[&amp;#xf276;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-map-signs
      
      --><span>[&amp;#xf277;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-mars
      
      --><span>[&amp;#xf222;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-mars-double
      
      --><span>[&amp;#xf227;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-mars-stroke
      
      --><span>[&amp;#xf229;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-mars-stroke-h
      
      --><span>[&amp;#xf22b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-mars-stroke-v
      
      --><span>[&amp;#xf22a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-maxcdn
      
      --><span>[&amp;#xf136;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-meanpath
      
      --><span>[&amp;#xf20c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-medium
      
      --><span>[&amp;#xf23a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-medkit
      
      --><span>[&amp;#xf0fa;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-meh-o
      
      --><span>[&amp;#xf11a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-mercury
      
      --><span>[&amp;#xf223;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-microphone
      
      --><span>[&amp;#xf130;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-microphone-slash
      
      --><span>[&amp;#xf131;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-minus
      
      --><span>[&amp;#xf068;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-minus-circle
      
      --><span>[&amp;#xf056;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-minus-square
      
      --><span>[&amp;#xf146;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-minus-square-o
      
      --><span>[&amp;#xf147;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-mobile
      
      --><span>[&amp;#xf10b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-mobile-phone
       
      --><span>[&amp;#xf10b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-money
      
      --><span>[&amp;#xf0d6;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-moon-o
      
      --><span>[&amp;#xf186;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-mortar-board
       
      --><span>[&amp;#xf19d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-motorcycle
      
      --><span>[&amp;#xf21c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-mouse-pointer
      
      --><span>[&amp;#xf245;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-music
      
      --><span>[&amp;#xf001;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-navicon
       
      --><span>[&amp;#xf0c9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-neuter
      
      --><span>[&amp;#xf22c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-newspaper-o
      
      --><span>[&amp;#xf1ea;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-object-group
      
      --><span>[&amp;#xf247;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-object-ungroup
      
      --><span>[&amp;#xf248;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-odnoklassniki
      
      --><span>[&amp;#xf263;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-odnoklassniki-square
      
      --><span>[&amp;#xf264;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-opencart
      
      --><span>[&amp;#xf23d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-openid
      
      --><span>[&amp;#xf19b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-opera
      
      --><span>[&amp;#xf26a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-optin-monster
      
      --><span>[&amp;#xf23c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-outdent
      
      --><span>[&amp;#xf03b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-pagelines
      
      --><span>[&amp;#xf18c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-paint-brush
      
      --><span>[&amp;#xf1fc;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-paper-plane
      
      --><span>[&amp;#xf1d8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-paper-plane-o
      
      --><span>[&amp;#xf1d9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-paperclip
      
      --><span>[&amp;#xf0c6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-paragraph
      
      --><span>[&amp;#xf1dd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-paste
       
      --><span>[&amp;#xf0ea;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-pause
      
      --><span>[&amp;#xf04c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-paw
      
      --><span>[&amp;#xf1b0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-paypal
      
      --><span>[&amp;#xf1ed;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-pencil
      
      --><span>[&amp;#xf040;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-pencil-square
      
      --><span>[&amp;#xf14b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-pencil-square-o
      
      --><span>[&amp;#xf044;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-phone
      
      --><span>[&amp;#xf095;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-phone-square
      
      --><span>[&amp;#xf098;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-photo
       
      --><span>[&amp;#xf03e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-picture-o
      
      --><span>[&amp;#xf03e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-pie-chart
      
      --><span>[&amp;#xf200;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-pied-piper
      
      --><span>[&amp;#xf1a7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-pied-piper-alt
      
      --><span>[&amp;#xf1a8;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-pinterest
      
      --><span>[&amp;#xf0d2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-pinterest-p
      
      --><span>[&amp;#xf231;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-pinterest-square
      
      --><span>[&amp;#xf0d3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-plane
      
      --><span>[&amp;#xf072;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-play
      
      --><span>[&amp;#xf04b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-play-circle
      
      --><span>[&amp;#xf144;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-play-circle-o
      
      --><span>[&amp;#xf01d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-plug
      
      --><span>[&amp;#xf1e6;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-plus
      
      --><span>[&amp;#xf067;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-plus-circle
      
      --><span>[&amp;#xf055;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-plus-square
      
      --><span>[&amp;#xf0fe;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-plus-square-o
      
      --><span>[&amp;#xf196;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-power-off
      
      --><span>[&amp;#xf011;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-print
      
      --><span>[&amp;#xf02f;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-puzzle-piece
      
      --><span>[&amp;#xf12e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-qq
      
      --><span>[&amp;#xf1d6;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-qrcode
      
      --><span>[&amp;#xf029;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-question
      
      --><span>[&amp;#xf128;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-question-circle
      
      --><span>[&amp;#xf059;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-quote-left
      
      --><span>[&amp;#xf10d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-quote-right
      
      --><span>[&amp;#xf10e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-ra
       
      --><span>[&amp;#xf1d0;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-random
      
      --><span>[&amp;#xf074;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-rebel
      
      --><span>[&amp;#xf1d0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-recycle
      
      --><span>[&amp;#xf1b8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-reddit
      
      --><span>[&amp;#xf1a1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-reddit-square
      
      --><span>[&amp;#xf1a2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-refresh
      
      --><span>[&amp;#xf021;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-registered
      
      --><span>[&amp;#xf25d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-remove
       
      --><span>[&amp;#xf00d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-renren
      
      --><span>[&amp;#xf18b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-reorder
       
      --><span>[&amp;#xf0c9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-repeat
      
      --><span>[&amp;#xf01e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-reply
      
      --><span>[&amp;#xf112;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-reply-all
      
      --><span>[&amp;#xf122;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-retweet
      
      --><span>[&amp;#xf079;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rmb
       
      --><span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-road
      
      --><span>[&amp;#xf018;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rocket
      
      --><span>[&amp;#xf135;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rotate-left
       
      --><span>[&amp;#xf0e2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rotate-right
       
      --><span>[&amp;#xf01e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-rouble
       
      --><span>[&amp;#xf158;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rss
      
      --><span>[&amp;#xf09e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rss-square
      
      --><span>[&amp;#xf143;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-rub
      
      --><span>[&amp;#xf158;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-ruble
       
      --><span>[&amp;#xf158;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-rupee
       
      --><span>[&amp;#xf156;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-safari
      
      --><span>[&amp;#xf267;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-save
       
      --><span>[&amp;#xf0c7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-scissors
      
      --><span>[&amp;#xf0c4;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-search
      
      --><span>[&amp;#xf002;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-search-minus
      
      --><span>[&amp;#xf010;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-search-plus
      
      --><span>[&amp;#xf00e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-sellsy
      
      --><span>[&amp;#xf213;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-send
       
      --><span>[&amp;#xf1d8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-send-o
       
      --><span>[&amp;#xf1d9;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-server
      
      --><span>[&amp;#xf233;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-share
      
      --><span>[&amp;#xf064;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-share-alt
      
      --><span>[&amp;#xf1e0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-share-alt-square
      
      --><span>[&amp;#xf1e1;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-share-square
      
      --><span>[&amp;#xf14d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-share-square-o
      
      --><span>[&amp;#xf045;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-shekel
       
      --><span>[&amp;#xf20b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-sheqel
       
      --><span>[&amp;#xf20b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-shield
      
      --><span>[&amp;#xf132;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-ship
      
      --><span>[&amp;#xf21a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-shirtsinbulk
      
      --><span>[&amp;#xf214;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-shopping-cart
      
      --><span>[&amp;#xf07a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sign-in
      
      --><span>[&amp;#xf090;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sign-out
      
      --><span>[&amp;#xf08b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-signal
      
      --><span>[&amp;#xf012;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-simplybuilt
      
      --><span>[&amp;#xf215;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sitemap
      
      --><span>[&amp;#xf0e8;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-skyatlas
      
      --><span>[&amp;#xf216;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-skype
      
      --><span>[&amp;#xf17e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-slack
      
      --><span>[&amp;#xf198;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-sliders
      
      --><span>[&amp;#xf1de;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-slideshare
      
      --><span>[&amp;#xf1e7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-smile-o
      
      --><span>[&amp;#xf118;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-soccer-ball-o
       
      --><span>[&amp;#xf1e3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort
      
      --><span>[&amp;#xf0dc;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-alpha-asc
      
      --><span>[&amp;#xf15d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-alpha-desc
      
      --><span>[&amp;#xf15e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-amount-asc
      
      --><span>[&amp;#xf160;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-amount-desc
      
      --><span>[&amp;#xf161;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-asc
      
      --><span>[&amp;#xf0de;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-desc
      
      --><span>[&amp;#xf0dd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-down
       
      --><span>[&amp;#xf0dd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-numeric-asc
      
      --><span>[&amp;#xf162;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-numeric-desc
      
      --><span>[&amp;#xf163;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sort-up
       
      --><span>[&amp;#xf0de;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-soundcloud
      
      --><span>[&amp;#xf1be;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-space-shuttle
      
      --><span>[&amp;#xf197;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-spinner
      
      --><span>[&amp;#xf110;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-spoon
      
      --><span>[&amp;#xf1b1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-spotify
      
      --><span>[&amp;#xf1bc;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-square
      
      --><span>[&amp;#xf0c8;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-square-o
      
      --><span>[&amp;#xf096;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-stack-exchange
      
      --><span>[&amp;#xf18d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-stack-overflow
      
      --><span>[&amp;#xf16c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-star
      
      --><span>[&amp;#xf005;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-star-half
      
      --><span>[&amp;#xf089;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-star-half-empty
       
      --><span>[&amp;#xf123;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-star-half-full
       
      --><span>[&amp;#xf123;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-star-half-o
      
      --><span>[&amp;#xf123;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-star-o
      
      --><span>[&amp;#xf006;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-steam
      
      --><span>[&amp;#xf1b6;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-steam-square
      
      --><span>[&amp;#xf1b7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-step-backward
      
      --><span>[&amp;#xf048;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-step-forward
      
      --><span>[&amp;#xf051;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-stethoscope
      
      --><span>[&amp;#xf0f1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-sticky-note
      
      --><span>[&amp;#xf249;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-sticky-note-o
      
      --><span>[&amp;#xf24a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-stop
      
      --><span>[&amp;#xf04d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-street-view
      
      --><span>[&amp;#xf21d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-strikethrough
      
      --><span>[&amp;#xf0cc;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-stumbleupon
      
      --><span>[&amp;#xf1a4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-stumbleupon-circle
      
      --><span>[&amp;#xf1a3;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-subscript
      
      --><span>[&amp;#xf12c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-subway
      
      --><span>[&amp;#xf239;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-suitcase
      
      --><span>[&amp;#xf0f2;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-sun-o
      
      --><span>[&amp;#xf185;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-superscript
      
      --><span>[&amp;#xf12b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-support
       
      --><span>[&amp;#xf1cd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-table
      
      --><span>[&amp;#xf0ce;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tablet
      
      --><span>[&amp;#xf10a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tachometer
      
      --><span>[&amp;#xf0e4;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tag
      
      --><span>[&amp;#xf02b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tags
      
      --><span>[&amp;#xf02c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tasks
      
      --><span>[&amp;#xf0ae;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-taxi
      
      --><span>[&amp;#xf1ba;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-television
      
      --><span>[&amp;#xf26c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-tencent-weibo
      
      --><span>[&amp;#xf1d5;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-terminal
      
      --><span>[&amp;#xf120;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-text-height
      
      --><span>[&amp;#xf034;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-text-width
      
      --><span>[&amp;#xf035;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-th
      
      --><span>[&amp;#xf00a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-th-large
      
      --><span>[&amp;#xf009;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-th-list
      
      --><span>[&amp;#xf00b;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-thumb-tack
      
      --><span>[&amp;#xf08d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-thumbs-down
      
      --><span>[&amp;#xf165;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-thumbs-o-down
      
      --><span>[&amp;#xf088;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-thumbs-o-up
      
      --><span>[&amp;#xf087;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-thumbs-up
      
      --><span>[&amp;#xf164;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-ticket
      
      --><span>[&amp;#xf145;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-times
      
      --><span>[&amp;#xf00d;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-times-circle
      
      --><span>[&amp;#xf057;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-times-circle-o
      
      --><span>[&amp;#xf05c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tint
      
      --><span>[&amp;#xf043;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-toggle-down
       
      --><span>[&amp;#xf150;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-toggle-left
       
      --><span>[&amp;#xf191;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-toggle-off
      
      --><span>[&amp;#xf204;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-toggle-on
      
      --><span>[&amp;#xf205;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-toggle-right
       
      --><span>[&amp;#xf152;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-toggle-up
       
      --><span>[&amp;#xf151;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-trademark
      
      --><span>[&amp;#xf25c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-train
      
      --><span>[&amp;#xf238;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-transgender
      
      --><span>[&amp;#xf224;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-transgender-alt
      
      --><span>[&amp;#xf225;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-trash
      
      --><span>[&amp;#xf1f8;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-trash-o
      
      --><span>[&amp;#xf014;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-tree
      
      --><span>[&amp;#xf1bb;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-trello
      
      --><span>[&amp;#xf181;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-tripadvisor
      
      --><span>[&amp;#xf262;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-trophy
      
      --><span>[&amp;#xf091;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-truck
      
      --><span>[&amp;#xf0d1;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-try
      
      --><span>[&amp;#xf195;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-tty
      
      --><span>[&amp;#xf1e4;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tumblr
      
      --><span>[&amp;#xf173;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-tumblr-square
      
      --><span>[&amp;#xf174;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-turkish-lira
       
      --><span>[&amp;#xf195;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-tv
       
      --><span>[&amp;#xf26c;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-twitch
      
      --><span>[&amp;#xf1e8;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-twitter
      
      --><span>[&amp;#xf099;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-twitter-square
      
      --><span>[&amp;#xf081;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-umbrella
      
      --><span>[&amp;#xf0e9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-underline
      
      --><span>[&amp;#xf0cd;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-undo
      
      --><span>[&amp;#xf0e2;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-university
      
      --><span>[&amp;#xf19c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-unlink
       
      --><span>[&amp;#xf127;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-unlock
      
      --><span>[&amp;#xf09c;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-unlock-alt
      
      --><span>[&amp;#xf13e;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-unsorted
       
      --><span>[&amp;#xf0dc;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-upload
      
      --><span>[&amp;#xf093;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-usd
      
      --><span>[&amp;#xf155;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-user
      
      --><span>[&amp;#xf007;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-user-md
      
      --><span>[&amp;#xf0f0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-user-plus
      
      --><span>[&amp;#xf234;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-user-secret
      
      --><span>[&amp;#xf21b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-user-times
      
      --><span>[&amp;#xf235;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-users
      
      --><span>[&amp;#xf0c0;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-venus
      
      --><span>[&amp;#xf221;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-venus-double
      
      --><span>[&amp;#xf226;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-venus-mars
      
      --><span>[&amp;#xf228;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-viacoin
      
      --><span>[&amp;#xf237;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-video-camera
      
      --><span>[&amp;#xf03d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-vimeo
      
      --><span>[&amp;#xf27d;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-vimeo-square
      
      --><span>[&amp;#xf194;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-vine
      
      --><span>[&amp;#xf1ca;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-vk
      
      --><span>[&amp;#xf189;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-volume-down
      
      --><span>[&amp;#xf027;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-volume-off
      
      --><span>[&amp;#xf026;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-volume-up
      
      --><span>[&amp;#xf028;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-warning
       
      --><span>[&amp;#xf071;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-wechat
       
      --><span>[&amp;#xf1d7;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-weibo
      
      --><span>[&amp;#xf18a;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-weixin
      
      --><span>[&amp;#xf1d7;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.3</small>
      <i class="fa"></i><!--
      fa-whatsapp
      
      --><span>[&amp;#xf232;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.0</small>
      <i class="fa"></i><!--
      fa-wheelchair
      
      --><span>[&amp;#xf193;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-wifi
      
      --><span>[&amp;#xf1eb;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-wikipedia-w
      
      --><span>[&amp;#xf266;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-windows
      
      --><span>[&amp;#xf17a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-won
       
      --><span>[&amp;#xf159;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-wordpress
      
      --><span>[&amp;#xf19a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-wrench
      
      --><span>[&amp;#xf0ad;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-xing
      
      --><span>[&amp;#xf168;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-xing-square
      
      --><span>[&amp;#xf169;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-y-combinator
      
      --><span>[&amp;#xf23b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-y-combinator-square
       
      --><span>[&amp;#xf1d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-yahoo
      
      --><span>[&amp;#xf19e;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.4</small>
      <i class="fa"></i><!--
      fa-yc
       
      --><span>[&amp;#xf23b;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.1</small>
      <i class="fa"></i><!--
      fa-yc-square
       
      --><span>[&amp;#xf1d4;]</span>
    </div>
    
    <div class="faBox">
      <small class="fa-version">4.2</small>
      <i class="fa"></i><!--
      fa-yelp
      
      --><span>[&amp;#xf1e9;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-yen
       
      --><span>[&amp;#xf157;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-youtube
      
      --><span>[&amp;#xf167;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-youtube-play
      
      --><span>[&amp;#xf16a;]</span>
    </div>
    
    <div class="faBox">
      
      <i class="fa"></i><!--
      fa-youtube-square
      
      --><span>[&amp;#xf166;]</span>
    </div>
    
  </div>