<!-- layout("/pages/layout/index.phtml") --> 

<div class="row imageCoverPage">
  <h1>imageCover</h1>

  <div class="testImageCover">
    
    <div class="imageCover first">
      <img src="/UI/images/cute_cats.jpg" alt="" />
    </div>
    <div class="imageCover second">
      <img src="/UI/images/cute_kittens.jpg" alt="" />
    </div>
    <div class="imageCover third">
      <img src="/UI/images/cute_kittens.jpg" alt="" />
    </div>
    <div class="imageCover fourth">
      <img src="/UI/images/kittens-parallax-2.jpg" alt="" />
    </div>
    <div class="imageCover fifth">
      <img src="/UI/images/kittens-parallax-3.jpg" alt="" />
    </div>
    
  </div>

</div>