<!-- layout("/pages/layout/index.phtml") --> 

<div class="row image-cover-page">
  <h1>image-cover</h1>

  <div class="test-image-cover">
    
    <div class="image-cover first">
      <img src="/UI/images/cute_cats.jpg" alt="" />
    </div>
    <div class="image-cover second">
      <img src="/UI/images/cute_kittens.jpg" alt="" />
    </div>
    <div class="image-cover third">
      <img src="/UI/images/cute_kittens.jpg" alt="" />
    </div>
    <div class="image-cover fourth">
      <img src="/UI/images/kittens-parallax-2.jpg" alt="" />
    </div>
    <div class="image-cover fifth">
      <img src="/UI/images/kittens-parallax-3.jpg" alt="" />
    </div>
    
  </div>

</div>
