<!-- layout("/pages/layout/index.phtml") --> 

<div class="row inputStuff">
  <h1>inputStuff</h1>
  <form>
    <fieldset>
      <label>
        <span>Kontokort nummer</span>
        <input type="text" data-format="creditcard" autocomplete="off" />
      </label>

      <!--<label>
        <span>File</span>
        <input type="file" name="file" />
      </label>-->
      
    </fieldset>
  </form>
</div>