<!-- layout("/pages/layout/index.phtml") --> 

<div class="row parallaxPage">
  <h1>Parallax</h1>

  <p>
    <a href="http://codepen.io/PetterBoozegunk/pen/QyNweL" target="_blank">Parallax on condepen</a>
  </p>

  <div class="parallax">
    <div style="background-image: url(http://loremflickr.com/300/300/kitten)">
      <!-- -->
    </div>
  </div>

  <div class="parallax">
    <div style="background-image: url(http://loremflickr.com/400/400/doctorwho)">
      <!-- -->
    </div>
  </div>

  <div class="parallax">
    <div style="background-image: url(http://loremflickr.com/500/500/fallout4)">
      <!-- -->
    </div>
  </div>

  <div class="row">
    
    <div class="col w50">
      <div class="parallax">
        <div style="background-image: url(http://loremflickr.com/600/600/dropkickmurphys)">
          <!-- -->
        </div>
      </div>
    </div>

    <div class="col w50">
      <div class="parallax">
        <div style="background-image: url(http://loremflickr.com/700/700/ramones)">
          <!-- -->
        </div>
      </div>
    </div>
    
  </div>
  
</div>