<!-- layout("/pages/layout/index.phtml") --> 

<div class="row parallaxPage">
  <h1>Parallax</h1>

  <div class="parallax">
    <div style="background-image: url(/UI/images/kittens-parallax-1.jpg)"> 
      <!-- -->
    </div>
  </div>

  <div class="parallax">
    <div style="background-image: url(/UI/images/kittens-parallax-2.jpg)">
      <!-- -->
    </div>
  </div>

  <div class="parallax">
    <div style="background-image: url(/UI/images/kittens-parallax-3.jpg)">
      <!-- -->
    </div>
  </div>

  <div class="row">
    
    <div class="col w50">
      <div class="parallax">
        <div style="background-image: url(/UI/images/cute_cats.jpg)">
          <!-- -->
        </div>
      </div>
    </div>

    <div class="col w50">
      <div class="parallax">
        <div style="background-image: url(/UI/images/cute_kittens.jpg)">
          <!-- -->
        </div>
      </div>
    </div>
    
  </div>
  
</div>