<!-- layout("/pages/layout/index.phtml") --> 

<h1>Spinners!</h1>
<p class="uses">
<a href="/UI/js/spinner.js">spinners.js</a> uses "<a href="http://fgnass.github.io/spin.js/">spin.js</a>"
</p>
            
<ol class="examples-list">
    <li>
        <div class="spinner-test1"> <!-- --> </div>
        <code class="html">
            &lt;div class="spinner-test1"&gt; &lt;!-- --&gt; &lt;/div&gt;
        </code>
        <code class="js">
            $(".spinner-test1").trigger("spinner:get");
        </code>
    </li>
    <li>
        <div class="spinner-test2"> <!-- --> </div>
        <code>
            <span class="multi-line-comment">
                A spinner will get the same color as the parent element (css) color.
                To get the right color in ie8 and below the color has to be a hex value (ex: '#ff0000/#f00' not 'red')
            </span>
 
        </code>
        <code class="html">
            &lt;div class="spinner-test2"&gt; &lt;!-- --&gt; &lt;/div&gt;
        </code>
        <code class="js">
            $(".spinnerTest2").trigger("spinner:get");
        </code>
    </li>
    <li>
        <div class="spinner-test3"> <!-- --> </div>

        <code class="html">
            &lt;div class="spinner-test3"&gt; &lt;!-- --&gt; &lt;/div&gt;
        </code>
        <code class="js">
            <span class="comment block"> The spinnerObj will overwrite the spinner defaults</span>

            var spinnerObj = {
                color: "#90ee90" <span class="comment"> lightgreen</span>
            };

            $(".spinner-test3").trigger("spinner:get", spinnerObj);
        </code>
    </li>
</ol>
