<!-- layout("/pages/layout/index.phtml") --> 

<h1>SpinnersCss</h1>

<p>Css + fontawsome spinners </p>
            
<ol class="examplesList spinnersCss">
    <li>
      <div class="spinner">test1</div>
    </li>
    <li>
      <div class="spinner">test2</div>
    </li>
    <li>
      <div class="spinner">test3</div>
    </li>
    <li>
      <div class="spinner">test4</div>
    </li>
    <li>
      <div class="spinner steps">test5</div>
    </li>
</ol>