<!-- layout("/pages/layout/styleguide_layout.phtml") --> 

<div class="mainContent styleguide">
    <div class="section">
      
        <h1>Styleguide - h1</h1>
        <h2>Styleguide - h2</h2>
        <h3>Styleguide - h3</h3>
        <h4>Styleguide - h4</h4>
        <h5>Styleguide - h5</h5>
        <h6>Styleguide - h6</h6>

      <p>
        P - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce molestie non leo ac ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras facilisis, tortor vel suscipit porttitor, felis risus pulvinar est, quis ultrices ex quam vel tortor. Proin lorem lorem, pulvinar at lorem id, ornare tempus nulla. Sed ac sagittis ante. Sed porta rutrum turpis, sed vulputate est maximus non. Cras sollicitudin accumsan nunc sed aliquet. Quisque dui diam, tincidunt in tellus vitae, iaculis vehicula dui. Mauris eu leo ac sem lacinia ullamcorper. Sed luctus nulla ultricies, sollicitudin orci nec, condimentum odio. Praesent at volutpat magna! Maecenas vel nunc vehicula, egestas libero in, vulputate lacus. Ut vulputate pulvinar tortor id condimentum.
      </p>
      <p>
        <a href="/">A - Link</a>
      </p>
    </div>
    <div class="section">
      <h2>Grid</h2>
      
      <!-- col-span 12 -->
      <div class="row outer-grid-wrap-row">
        
        <div class="col col-span12">
          <div class="box">
            <h3>col-span12</h3>
          </div>
        </div>
        
      </div>

      <!-- col-span 1 + 11 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span1">
          <div class="box">
            <h3>col-span1</h3>
          </div>
        </div>
        
        <div class="col col-span11">
          <div class="box">
            <h3>col-span11</h3>
          </div>
        </div>

      </div>

      <!-- col-span 2 + 10 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span2">
          <div class="box">
            <h3>col-span2</h3>
          </div>
        </div>

        <div class="col col-span10">
          <div class="box">
            <h3>col-span10</h3>
          </div>
        </div>

      </div>


      <!-- col-span 3 + 9 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span3">
          <div class="box">
            <h3>col-span3</h3>
          </div>
        </div>

        <div class="col col-span9">
          <div class="box">
            <h3>col-span9</h3>
          </div>
        </div>

      </div>

      <!-- col-span 4 + 8 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span4">
          <div class="box">
            <h3>col-span4</h3>
          </div>
        </div>

        <div class="col col-span8">
          <div class="box">
            <h3>col-span8</h3>
          </div>
        </div>

      </div>


      <!-- col-span 5 + 7 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span5">
          <div class="box">
            <h3>col-span5</h3>
          </div>
        </div>

        <div class="col col-span7">
          <div class="box">
            <h3>col-span7</h3>
          </div>
        </div>

      </div>


      <!-- col-span 6 + 6 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span6">
          <div class="box">
            <h3>col-span6</h3>
          </div>
        </div>

        <div class="col col-span6">
          <div class="box">
            <h3>col-span6</h3>
          </div>
        </div>

      </div>
      
      <!-- col-span 3 + 6 + 3 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span3">
          <div class="box">
            <h3>col-span3</h3>
          </div>
        </div>

        <div class="col col-span6">
          <div class="box">
            <h3>col-span6</h3>
          </div>
        </div>


        <div class="col col-span3">
          <div class="box">
            <h3>col-span3</h3>
          </div>
        </div>

      </div>

      <!-- col-span 4 + 4 + 4 -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span4">
          <div class="box">
            <h3>col-span4</h3>
          </div>
        </div>
        
        <div class="col col-span4">
          <div class="box">
            <h3>col-span4</h3>
          </div>
        </div>
        
        <div class="col col-span4">
          <div class="box">
            <h3>col-span4</h3>
          </div>
        </div>
        
      </div>

      <!-- col-span 3 + 9 (with 3 cols) -->
      <div class="row outer-grid-wrap-row">

        <div class="col col-span3">
          <div class="box">
            <h3>col-span3</h3>
          </div>
        </div>

        <div class="col col-span9">
          <div class="box row outer-grid-wrap-row">
            <h3>col-span9 + 3 nested cols</h3>

            <div class="col col-span3">
              <div class="box">
              <h4>col-span 3</h4>
              </div>
            </div>
            <div class="col col-span3">
              <div class="box">
                <h4>col-span 3</h4>
              </div>
            </div>
            <div class="col col-span3">
              <div class="box">
                <h4>col-span 3</h4>
              </div>
            </div>
            
          </div>
        </div>

      </div>

    </div>

  <div class="section row">
    <h2>Main layout</h2>
    <div class="row outer-grid-wrap-row">
      <nav class="col col-span2">
        <h3>[nav - col-span 2]</h3>
      </nav>
      <article class="col col-span7">
        <h3>[article - col-span 7]</h3>
      </article>
      <aside class="col col-span3">
        <h3>[aside - col-span 3]</h3>
      </aside>
    </div>
  </div>
  
</div>
