<!-- layout("/pages/layout/styleguide_layout.phtml") --> 

<div class="mainContent styleguide">
    <div class="section">
      
        <h1>Styleguide - h1</h1>
        <h2>Styleguide - h2</h2>
        <h3>Styleguide - h3</h3>
        <h4>Styleguide - h4</h4>
        <h5>Styleguide - h5</h5>
        <h6>Styleguide - h6</h6>

      <p>
        P - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce molestie non leo ac ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras facilisis, tortor vel suscipit porttitor, felis risus pulvinar est, quis ultrices ex quam vel tortor. Proin lorem lorem, pulvinar at lorem id, ornare tempus nulla. Sed ac sagittis ante. Sed porta rutrum turpis, sed vulputate est maximus non. Cras sollicitudin accumsan nunc sed aliquet. Quisque dui diam, tincidunt in tellus vitae, iaculis vehicula dui. Mauris eu leo ac sem lacinia ullamcorper. Sed luctus nulla ultricies, sollicitudin orci nec, condimentum odio. Praesent at volutpat magna! Maecenas vel nunc vehicula, egestas libero in, vulputate lacus. Ut vulputate pulvinar tortor id condimentum.
      </p>
      <p>
        <a href="/">A - Link</a>
      </p>
    </div>
    <div class="section">
      <h2>Grid</h2>
      
      <!-- colspan 12 -->
      <div class="row outerGridWrapRow">
        
        <div class="col colSpan12">
          <div class="box">
            <h3>colspan12</h3>
          </div>
        </div>
        
      </div>

      <!-- colspan 1 + 11 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan1">
          <div class="box">
            <h3>colspan1</h3>
          </div>
        </div>
        
        <div class="col colSpan11">
          <div class="box">
            <h3>colspan11</h3>
          </div>
        </div>

      </div>

      <!-- colspan 2 + 10 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan2">
          <div class="box">
            <h3>colspan2</h3>
          </div>
        </div>

        <div class="col colSpan10">
          <div class="box">
            <h3>colspan10</h3>
          </div>
        </div>

      </div>


      <!-- colspan 3 + 9 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan3">
          <div class="box">
            <h3>colspan3</h3>
          </div>
        </div>

        <div class="col colSpan9">
          <div class="box">
            <h3>colspan9</h3>
          </div>
        </div>

      </div>

      <!-- colspan 4 + 8 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan4">
          <div class="box">
            <h3>colspan4</h3>
          </div>
        </div>

        <div class="col colSpan8">
          <div class="box">
            <h3>colspan8</h3>
          </div>
        </div>

      </div>


      <!-- colspan 5 + 7 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan5">
          <div class="box">
            <h3>colspan5</h3>
          </div>
        </div>

        <div class="col colSpan7">
          <div class="box">
            <h3>colspan7</h3>
          </div>
        </div>

      </div>


      <!-- colspan 6 + 6 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan6">
          <div class="box">
            <h3>colspan6</h3>
          </div>
        </div>

        <div class="col colSpan6">
          <div class="box">
            <h3>colspan6</h3>
          </div>
        </div>

      </div>
      
      <!-- colspan 3 + 6 + 3 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan3">
          <div class="box">
            <h3>colspan3</h3>
          </div>
        </div>

        <div class="col colSpan6">
          <div class="box">
            <h3>colspan6</h3>
          </div>
        </div>


        <div class="col colSpan3">
          <div class="box">
            <h3>colspan3</h3>
          </div>
        </div>

      </div>

      <!-- colspan 4 + 4 + 4 -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan4">
          <div class="box">
            <h3>colspan4</h3>
          </div>
        </div>
        
        <div class="col colSpan4">
          <div class="box">
            <h3>colspan4</h3>
          </div>
        </div>
        
        <div class="col colSpan4">
          <div class="box">
            <h3>colspan4</h3>
          </div>
        </div>
        
      </div>

      <!-- colspan 3 + 9 (with 3 cols) -->
      <div class="row outerGridWrapRow">

        <div class="col colSpan3">
          <div class="box">
            <h3>colspan3</h3>
          </div>
        </div>

        <div class="col colSpan9">
          <div class="box row outerGridWrapRow">
            <h3>colspan9 + 3 nested cols</h3>

            <div class="col colSpan3">
              <div class="box">
              <h4>Colspan 3</h4>
              </div>
            </div>
            <div class="col colSpan3">
              <div class="box">
                <h4>Colspan 3</h4>
              </div>
            </div>
            <div class="col colSpan3">
              <div class="box">
                <h4>Colspan 3</h4>
              </div>
            </div>
            
          </div>
        </div>

      </div>

    </div>

  <div class="section row">
    <h2>Main layout</h2>
    <div class="row outerGridWrapRow">
      <nav class="col colSpan2">
        <h3>[nav - colspan 2]</h3>
      </nav>
      <article class="col colSpan7">
        <h3>[article - colspan 7]</h3>
      </article>
      <aside class="col colSpan3">
        <h3>[aside - colspan 3]</h3>
      </aside>
    </div>
  </div>
  
</div>