<!-- layout("/pages/layout/index.phtml") --> 

<div class="row video">
  <h1>Video</h1>
  <div class="video-container">
    <div class="topBottomFade">
      <video autoplay="" muted="" poster="/UI/video/poster.png">
        <source src="/UI/video/devstories.webm" type="video/webm;codecs=&quot;vp8, vorbis&quot;"></source>
        <source src="/UI/video/devstories.mp4" type="video/mp4;codecs=&quot;avc1.42E01E, mp4a.40.2&quot;"></source>
        <!--<track src="/UI/video/devstories-en.vtt" label="English subtitles" kind="subtitles" srclang="en" default=""></track>-->
      </video>
    </div>
  </div>
</div>